FROM python:3.11-slim AS deps

ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV POETRY_VERSION 1.3.1

WORKDIR /tmp

RUN pip install "poetry==$POETRY_VERSION" && poetry config virtualenvs.create false

COPY poetry.lock pyproject.toml ./

RUN poetry install --no-interaction --no-ansi

FROM deps AS dev

WORKDIR /backend

ENTRYPOINT [ "uvicorn", "fastcord.app:app", "--reload", "--host", "0.0.0.0", "--port", "5000"]
