services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: kvdomingo/fastcord-api:latest
    env_file: .env
    volumes:
      - .:/backend
    depends_on:
      - db

  proxy:
    image: bitnami/nginx:1.21.6
    environment:
      NGINX_HTTP_PORT_NUMBER: ${PORT}
    volumes:
      - ./proxy:/opt/bitnami/nginx/conf/server_blocks:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastcord.rule=Host(`api.fastcord.localhost`)"
      - "traefik.http.routers.fastcord.entrypoints=http"
      - "traefik.http.routers.fastcord.middlewares=secured@file"
      - "traefik.docker.network=gateway"
      - "traefik.http.services.fastcord.loadbalancer.server.port=${PORT}"
    restart: unless-stopped
    networks:
      - default
      - gateway
    depends_on:
      - backend

  db:
    image: bitnami/mongodb:5.0.18
    environment:
      MONGODB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    volumes:
      - db-data:/bitnami/mongodb
    restart: unless-stopped

  express:
    image: mongo-express:0.54
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: false
      ME_CONFIG_MONGODB_AUTH_DATABASE: ${MONGODB_DATABASE}
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastcord-express.rule=Host(`express.fastcord.localhost`)"
      - "traefik.http.routers.fastcord-express.entrypoints=http"
      - "traefik.http.routers.fastcord-express.middlewares=secured@file"
      - "traefik.docker.network=gateway"
      - "traefik.http.services.fastcord-express.loadbalancer.server.port=8081"
    networks:
      - default
      - gateway

networks:
  gateway:
    external: true

volumes:
  db-data: {}
