version: '3'

env:
  NAME: fastcord-api-dev

dotenv:
  - .env

tasks:
  default:
    desc: Build and start containers
    cmds:
      - docker compose --project-name {{.NAME}} up --detach --build --remove-orphans {{.CLI_ARGS}}

  reload-proxy:
    desc: Reload proxy config
    cmds:
      - docker compose --project-name {{.NAME}} exec -- proxy nginx -s reload

  exec:
    desc: Execute command in specified container
    cmds:
      - docker compose --project-name {{.NAME}} exec -- {{.CLI_ARGS}}

  restart:
    desc: Restart all containers
    cmds:
      - docker compose --project-name {{.NAME}} restart {{.CLI_ARGS}}

  logs:
    desc: Show Docker logs
    cmds:
      - docker compose --project-name {{.NAME}} logs --follow {{.CLI_ARGS}}

  shutdown:
    desc: Stop all containers
    cmds:
      - docker compose --project-name {{.NAME}} stop {{.CLI_ARGS}}

  clean:
    desc: Stop and remove all containers
    cmds:
      - docker compose --project-name {{.NAME}} down --remove-orphans {{.CLI_ARGS}}

  makemigrations:
    desc: Create migration file
    cmds:
      - docker compose --project-name {{.NAME}} exec backend alembic revision --autogenerate -m {{.CLI_ARGS}}

  migrate:
    desc: Create migration file
    cmds:
      - docker compose --project-name {{.NAME}} exec backend alembic upgrade head
