"""add order fields to channels

Revision ID: a13c6421f024
Revises: 5a4cdcbe4019
Create Date: 2023-08-27 18:02:42.296298

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a13c6421f024"
down_revision: Union[str, None] = "5a4cdcbe4019"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "channel", sa.Column("order", sa.Integer(), autoincrement=True, nullable=False)
    )
    op.add_column(
        "channel_group",
        sa.Column("order", sa.Integer(), autoincrement=True, nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("channel_group", "order")
    op.drop_column("channel", "order")
    # ### end Alembic commands ###
