"""create initial models

Revision ID: 3d8037b0c18e
Revises: 
Create Date: 2023-08-26 15:45:03.342736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3d8037b0c18e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guild",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("avatar", sa.String(), nullable=True),
        sa.Column("banner", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_guild_created"), "guild", ["created"], unique=False)
    op.create_index(op.f("ix_guild_id"), "guild", ["id"], unique=False)
    op.create_table(
        "channel",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=5), nullable=False),
        sa.Column("guild_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name", "type", "guild_id", name="unique_channel_names_types_per_guild"
        ),
    )
    op.create_index(op.f("ix_channel_created"), "channel", ["created"], unique=False)
    op.create_index(op.f("ix_channel_id"), "channel", ["id"], unique=False)
    op.create_table(
        "emoji",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("name", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("guild_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "guild_id", name="unique_emoji_names_per_guild"),
    )
    op.create_index(op.f("ix_emoji_created"), "emoji", ["created"], unique=False)
    op.create_index(op.f("ix_emoji_id"), "emoji", ["id"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("discriminator", sa.Integer(), nullable=False),
        sa.Column("avatar", sa.String(), nullable=True),
        sa.Column(
            "availability_status",
            sa.Enum(
                "ONLINE", "DO_NOT_DISTURB", "IDLE", "OFFLINE", name="availabilitystatus"
            ),
            nullable=False,
        ),
        sa.Column("status_message", sa.String(length=32), nullable=True),
        sa.Column("status_emoji_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["status_emoji_id"],
            ["emoji.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "username", "discriminator", name="unique_username_discriminator"
        ),
    )
    op.create_index(op.f("ix_user_created"), "user", ["created"], unique=False)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "friendship_association_table",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("friend_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["friend_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "friend_id"),
        sa.UniqueConstraint("user_id", "friend_id", name="unique_friendship"),
    )
    op.create_table(
        "message",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("content", sa.String(length=2048), nullable=False),
        sa.Column("author_id", sa.String(), nullable=False),
        sa.Column("channel_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_created"), "message", ["created"], unique=False)
    op.create_index(op.f("ix_message_id"), "message", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_id"), table_name="message")
    op.drop_index(op.f("ix_message_created"), table_name="message")
    op.drop_table("message")
    op.drop_table("friendship_association_table")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_index(op.f("ix_user_created"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_emoji_id"), table_name="emoji")
    op.drop_index(op.f("ix_emoji_created"), table_name="emoji")
    op.drop_table("emoji")
    op.drop_index(op.f("ix_channel_id"), table_name="channel")
    op.drop_index(op.f("ix_channel_created"), table_name="channel")
    op.drop_table("channel")
    op.drop_index(op.f("ix_guild_id"), table_name="guild")
    op.drop_index(op.f("ix_guild_created"), table_name="guild")
    op.drop_table("guild")
    # ### end Alembic commands ###
